name: vida_organizada
description: Asistente personal todo en uno para gestionar finanzas, metas, proyectos y más.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  glassmorphism: ^3.0.0
  
  # Estado
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  get_it: ^7.6.4
  
  # Base de datos
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navegador web
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.1
  
  # Analíticos y gráficos
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^29.2.4
  
  # Utilidades
  intl: 0.19.0  # Actualizado para compatibilidad con flutter_localizations
  http: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

# Configuración para el icono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png
    # Descomenta estas líneas cuando tengas estos directorios listos
    # - assets/images/
    # - assets/lottie/

  # Descomenta estas líneas cuando tengas las fuentes listas
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700