name: Build and Release Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze || true

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: VidaOrganizada-APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          name: VidaOrganizada ${{ github.ref_name }}
          body: |
            # VidaOrganizada ${{ github.ref_name }}
            
            Nueva versión de VidaOrganizada, tu asistente personal todo-en-uno.
            
            ## Cambios en esta versión:
            - Mejoras en el dashboard
            - Corrección de errores
            - Optimizaciones de rendimiento